name: build kexec
on: [ push, workflow_dispatch ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 13
    - uses: nixbuild/nix-quick-install-action@master
      with:
        nix_conf: |
          experimental-features = nix-command flakes
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.nixos.org

    # - run: |
    #     mkdir -m 0755  ~/.ssh
    #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
    #     chmod 600 ~/.ssh/id_ed25519
    
    # - run: |
    #     KEXEC_X86_64=$(nix build --no-link --print-out-paths .#nixosConfigurations.kexec-x86_64.config.system.build.kexec)
    #     cp -Lr --no-preserve=all $KEXEC_X86_64 artifact1   
    
    # Details: github:mlyxshi/flake/host/oracle/us1.nix
    # Build aarch64 on Oracle ARM
    # - run: |
    #     KEXEC_AARCH64=$(ssh -o StrictHostKeyChecking=no root@us1.mlyxshi.com buildkexec)
    #     rsync -L -e "ssh -o StrictHostKeyChecking=no" root@us1.mlyxshi.com:$KEXEC_AARCH64/*  artifact2/

    # - uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: "latest"
    #     prerelease: true
    #     files: |
    #       artifact1/*
